name: Transfer Issue
on:
  issues:
    types: [opened]

jobs:
  transfer_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Transfer Issue to Private Repo
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.issues.create({
              owner: 'pcarberry-rei',
              repo: 'https://github.com/pcarberry-REI/Venture-Studio',
              title: context.payload.issue.title,
              body: `Transferred from public issue:\n\n${context.payload.issue.body}\n\n[Original issue](${context.payload.issue.html_url})`,
              labels: context.payload.issue.labels.map(label => label.name),
            });

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'Thank you for your submission! This issue has been transferred to our internal team.'
            });

            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            });
